# version: '3.8'
services:
  global-think:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: global-think
    command: npm run start:prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
